
enyo.depends(
  'source/utils/AppSettings.js',
  'source/database/persistence/persistence.js',
  'source/database/persistence/persistence.store.sql.js',
  'source/database/persistence/persistence.store.websql.js',
  'source/database/persistence/persistence.search.js',
  'stylesheets/bombajob.css',
  'source/utils/funcs.js',
  'source/screens/BombaJob.js',
  'source/screens/Loading.js',
  'source/screens/NewestOffers.js',
  'source/screens/Jobs.js',
  'source/screens/People.js',
  'source/screens/Categories.js',
  'source/screens/OfferDetails.js',
  'source/screens/OfferMessage.js',
  'source/screens/Post.js',
  'source/screens/Search.js',
  'source/screens/SearchResults.js',
  'source/screens/Preferences.js',
  'source/screens/About.js'
);