
enyo.depends(
  'source/database/persistence/persistence.js',
  'source/database/persistence/persistence.store.sql.js',
  'source/database/persistence/persistence.store.websql.js',
  "source/utils/datetime.js",
  "stylesheets/bombajob.css",
  "source/utils/AppSettings.js",
  "source/screens/BombaJob.js",
  "source/screens/Loading.js",
  "source/screens/NewestOffers.js",
  "source/screens/Jobs.js",
  "source/screens/People.js",
  "source/screens/Categories.js",
  "source/screens/OfferDetails.js",
  "source/screens/Post.js",
  "source/screens/Search.js",
  "source/screens/Preferences.js",
  "source/screens/About.js"
);